
name: Run KuCoin Bots

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Scanner
      run: python scanner/kucoin_scanner.py
    - name: Run Watcher
      run: python watcher/kucoin_whale_watcher.py
